spring:
  graphql:
    path: /graphql
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    show-sql: true
  datasource:
    url: jdbc:h2:./build/database/db;AUTO_SERVER=TRUE
    username: user
    password: password
  devtools:
    livereload:
      enabled: false
  data:
    rest:
      detection-strategy: annotated
      default-media-type: application/json
  logging:
    level:
      org:
        springframework:
          graphql: DEBUG
          r2dbc: DEBUG

  flyway:
    baseline-on-migrate: true